name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: skylyrac/blocksds:slim-v1.16.0
    steps:
    - uses: actions/checkout@v4
    - name: make
      id: make
      working-directory: nds
      run: make
    - name: Publish build to GH Actions
      uses: actions/upload-artifact@v4
      with:
        path: |
